@startuml quoridor

' config includes
!include config/styles.iuml

' class diagram (https://plantuml.com/class-diagram)
package app {
    package common {
        class Position <<leaf>> {
            - x: int {readOnly}
            - y: int {readOnly}
            --
            + Position(x: int, y: int)
            + isAlignedTo(other: Position): boolean
            + isAdjacentTo(other: Position): boolean
            + isAdjacentTo(other: Position, orientation: Orientation): boolean
            + x(): int
            + y(): int
        }

        enum Orientation <<enumeration>> {
            + HORIZONTAL
            + VERTICAL
            --
            + opposite(): Orientation
        }
    }

    package exception {
        package setup {
            class SetupException <<exception>> {
                + SetupException(error: SetupError)
                + getError(): SetupError
            }
            SetupException *-- "1" SetupError : - error: SetupError {readOnly}

            enum SetupError <<enumeration>> {
                + INVALID_PLAYER_COUNT
            }
        }

        package turn {
            class TurnException <<exception>> {
                + TurnException(error: TurnError)
                + getError(): TurnError
            }
            TurnException *-- "1" TurnError : - error: TurnError {readOnly}

            enum TurnError <<enumeration>> {
                + NOT_CURRENT_PLAYER
                + INVALID_MOVEMENT
                + NO_WALLS_REMAINING
                + INVALID_PLACEMENT
                + GAME_ALREADY_FINISHED
            }
        }
    }

    package game {
        class Board {
            # Board(pawnCount: int)
            - createFields()
            + getFields(): Field[][]
            - createPawns(pawnCount: int)
            + movePawn(pawn: Pawn, destination: Field)
            + getPawns(): List<Pawn>
            + placeWall(wall: Wall)
            - removeNeighbor(a: Field, b: Field)
            + getWalls(): Set<Wall>
        }
        Board *-- "81" Field : - fields: Field[][] {readOnly}
        Board *-- "2..4" Pawn : - pawns: List<Pawn> {readOnly}
        Board *-- "*" Wall : - walls: Set<Wall> {readOnly}

        class Field {
            # Field(position: Position)
            + getPosition(): Position
            # addNeighbor(field: Field)
            # removeNeighbor(field: Field)
            + getNeighbors(): Set<Field>
            # setPawn(pawn: Pawn)
            + hasPawn(): boolean
            + getPawn(): Pawn
        }
        Field *-- "1" app.common.Position : - position: Position {readOnly}
        Field --> "1..4" Field : - neighbors: Set<Field> {readOnly}
        Field --> "0..1" Pawn : - pawn: Pawn

        class Pawn {
            # Pawn(startingField: Field, finishFields: Set<Field>)
            # setField(field: Field)
            + getField(): Field
            + hasReachedFinish(): boolean
            + getFinishFields(): Set<Field>
        }
        Pawn --> "1" Field : - field: Field
        Pawn --> "9" Field : - finishFields: Set<Field> {readOnly}

        class Wall <<leaf>> {
            + Wall(position: Position, orientation: Orientation)
            + position(): Position
            + orientation(): Orientation
        }
        Wall *-- "1" app.common.Position : - position: Position {readOnly}
        Wall *-- "1" app.common.Orientation : - orientation: Orientation {readOnly}

        class Game {
            - currentPlayerIndex: int
            - finished: boolean
            --
            + create(playerCount): Game {static}
            - Game(playerCount: int)
            + getBoard(): Board
            - createPlayers(playerCount: int)
            + getCurrentPlayer(): Player
            + getPlayers(): List<Player>
            - registerTurnHandlers()
            - getTurnHandler(turn: Turn): TurnHandler<Turn>
            + executeTurn(turn: Turn)
            - finishGame(winner: Player)
            - nextPlayer()
            + validateTurn(turn: Turn): TurnError
            + generateValidTurns(player: Player): Set<Turn>
            + hasValidTurns(player: Player): boolean
            + getTurnHistory(): Stack<Turn>
            + isFinished(): boolean
            + getWinner(): Player
        }
        Game *-- "1" Board : - board: Board {readOnly}
        Game *-- "2..4" Player : - players: List<Player> {readOnly}
        Game *-- "*" app.turn.TurnHandler : - turnHandlers: Map<Class<?: Turn>, TurnHandler<?>> {readOnly}
        Game *-- "*" app.turn.TurnGenerator : - turnGenerators: List<TurnGenerator<?>> {readOnly}
        Game *-- "*" app.turn.TurnAvailability : - turnAvailabilitys: List<TurnAvailability<?>> {readOnly}
        Game --> "*" app.turn.Turn : - turnHistory: Stack<Turn> {readOnly}
        Game --> "0..1" Player : - winner: Player
        Game ..> app.exception.setup.SetupException : throws
        Game ..> app.exception.turn.TurnException : throws

        class Player {
            - wallCount: int
            --
            # Player(pawn: Pawn, wallCount: int)
            + hasWon(): boolean
            + getPawn(): Pawn
            + reduceWallCount()
            + hasWallsRemaining(): boolean
            + getWallCount(): int
        }
        Player o-- "1" Pawn : - pawn: Pawn {readOnly}
    }

    package turn {
        package operation {
            class MovePawnTurn <<leaf>> {
                + MovePawnTurn(player: Player, destination: Field)
                + player(): Player
                + destination(): Field
            }
            app.turn.Turn <|.. MovePawnTurn
            MovePawnTurn --> "1" app.game.Player : - player: Player {readOnly}
            MovePawnTurn --> "1" app.game.Field : - destination: Field {readOnly}

            class PlaceWallTurn <<leaf>> {
                + PlaceWallTurn(player: Player, wall: Wall)
                + player(): Player
                + wall(): Wall
            }
            app.turn.Turn <|.. PlaceWallTurn
            PlaceWallTurn --> "1" app.game.Player : - player: Player {readOnly}
            PlaceWallTurn --> "1" app.game.Wall : - wall: Wall {readOnly}

            class NoOperationTurn <<leaf>> {
                + NoOperationTurn(player: Player)
                + player(): Player
            }
            app.turn.Turn <|.. NoOperationTurn
            NoOperationTurn --> "1" app.game.Player : - player: Player {readOnly}
        }

        package handler {
            class MovePawnTurnHandler {
                + execute(board: Board, turn: MovePawnTurn)
                + validate(board: Board, turn: MovePawnTurn): TurnError
                - validateMovement(board: Board, pawn: Pawn, destination: Field): boolean
                + generate(player: Player): Stream<MovePawnTurn>
                - generateMovements(current: Field): Stream<Field>
                - generateMovementsAtNeighbor(current: Field, neighbor: Field): Stream<Field>
                + any(player: Player): boolean
            }
            app.turn.TurnHandler <|.. MovePawnTurnHandler : <<bind>> <T -> MovePawnTurn>
            app.turn.TurnGenerator <|.. MovePawnTurnHandler : <<bind>> <T -> MovePawnTurn>
            app.turn.TurnAvailability <|.. MovePawnTurnHandler : <<bind>> <T -> MovePawnTurn>

            class PlaceWallTurnHandler {
                + execute(board: Board, turn: PlaceWallTurn)
                + validate(board: Board, turn: PlaceWallTurn): TurnError
                - validatePlacement(board: Board, wall: Wall): boolean
                + any(player: Player): boolean
            }
            app.turn.TurnHandler <|.. PlaceWallTurnHandler : <<bind>> <T -> PlaceWallTurn>
            app.turn.TurnAvailability <|.. PlaceWallTurnHandler : <<bind>> <T -> PlaceWallTurn>

            class NoOperationTurnHandler {
                + execute(board: Board, turn: NoOperationTurn)
                + validate(board: Board, turn: NoOperationTurn): TurnError
            }
            app.turn.TurnHandler <|.. NoOperationTurnHandler : <<bind>> <T -> NoOperationTurn>
        }

        interface Turn <<interface>> {
            + player(): Player {abstract}
        }

        interface TurnHandler<T: Turn> <<interface>> {
            + execute(board: Board, turn: T) {abstract}
            + validate(board: Board, turn: T): TurnError {abstract}
        }

        interface TurnGenerator<T: Turn> <<interface>> {
            + generate(player: Player): Stream<T> {abstract}
        }

        interface TurnAvailability<T: Turn> <<interface>> {
            + any(player: Player): boolean {abstract}
        }
    }
}

@enduml
